log:
    get_csv_fn: get_csv.log
    level: logging.INFO
    maxBytes: 50000000
    backupCount: 20
    notify_to: ["crebdream@gmail.com"]

general:
    get_s3_csv_files: >
       aws s3 ls dreamscsv --human-readable --summarize
